
---
version: '3.4'
services:

  bootnode:
    build:
      context: brownie/.
      args:
        BROWNIE_VERSION: ${BROWNIE_VERSION}
    image: ${DOCKER_IMAGE}/brownie:${BROWNIE_VERSION}
    environment:
      - BROWNIE_PUBLIC_KEY_DIRECTORY=${BROWNIE_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint: /opt/brownie/start.sh run yearn exporter --network mainnet
    volumes:
      - public-keys:${BROWNIE_PUBLIC_KEY_DIRECTORY}
      - ./config/brownie/config.toml:/config/config.toml
      - ./config/brownie/log-config.xml:/config/log-config.xml
      - ./logs/brownie:/var/log/
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  redis:
    image: redis:alpine

  elasticsearch:
    build: ./elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_COLLECTION_ENABLED: "true"
      SERVER_NAME: "localhost"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5601:5601/tcp

  logstash:
    build: ./logstash
    environment:
      - ES_HOST=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch

  filebeat:
    build: ./filebeat
    environment:
      - ENV_NAME=dev
      - IP_ADDRESS=127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./logs/brownie/:/var/log/brownie/

  metricbeat:
    build: ./metricbeat
    environment:
      - ENV_NAME=dev
      - IP_ADDRESS=127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    links:
      - redis

volumes:
  public-keys:

  prometheus:

  grafana:
