{
 "title": "APY Overview",
 "description": "This dashboard give you an overview of net apy for vaults",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "v1 Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(yearn{param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(yearn_vault{param=\"pricePerShare\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v1 Net APY - Weekly Compounding",
   "type": "graph",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((delta(yearn{param=\"share price\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "v2 Net APY - Weekly Compouding",
   "type": "graph",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((delta(yearn_vault{param=\"pricePerShare\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "y.curve.fi Earn v2 Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(iearn{param=\"price per share\", vault=~\".*v2\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "busd.curve.fi Earn v3 Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(iearn{param=\"price per share\", vault=~\".*v3\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn Net APY - Weekly Compouding",
   "type": "graph",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((delta(iearn{param=\"price per share\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Experimental Vault's Net APY - Weekly Compounding ",
   "type": "bargauge",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(((delta(yearn_experimental{param=\"pricePerShare\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ) ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Experimental Vault's Net APY - Weekly Compouding",
   "type": "graph",
   "description": "This looks at the share price rate of increase and factors in compounding on a weekly basis. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((delta(yearn_experimental{param=\"pricePerShare\"}[1w]) + 1) ^ (1/7)) ^ 365 - 1 < 100 ",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}