{
 "title": "Curve Vaults' APY",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CRV APY",
   "type": "graph",
   "description": "This shows the curve vault's base APY. This is their current unboosted apys",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"crv apy\"} < 500",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Relative Weight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"relative weight\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Relative Weight - Current",
   "type": "graph",
   "description": "This show the curve vaults and their % of gauge weight compared to the rest of all the curve pools",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Gauge Weight relative to all curve pools"
    }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"relative weight\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "CRV Price",
   "type": "graph",
   "description": "CRV price effects curve vault yields. Generally higher the price of crv the higher the yields",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"crv price\", vault=\"curve.fi/3pool\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}