{
 "title": "Earn Overview",
 "description": "This dashboard provides a general overview on all of Earn's products.",
 "tags": [ "Earn" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "TVL Earn v2 & v3",
   "type": "stat",
   "description": "Total Valued Locked in Yearn's yEarn products. This sum includes y.curve.fi (v2) & busd.curve.fi (v3).",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "y.curve.fi (v2) Earn - TVL",
   "type": "graph",
   "description": "TVL locked in Earn v2. You can shift + right-click on v2 AUM to exclude it from the graph (making it look nicer)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"tvl\", vault=~\".*v2\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(iearn{param=\"tvl\", vault=~\".*v2\"})",
     "legendFormat": "iEarn v2 AUM"
    }
   ]
  },
  {
   "title": "busd.curve.fi (v3) Earn - TVL",
   "type": "graph",
   "description": "TVL locked in Earn v3. You can shift + right-click on v3 AUM to exclude it from the graph (making it look nicer)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"tvl\", vault=~\".*v3\"}",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "sum(iearn{param=\"tvl\", vault=~\".*v3\"})",
     "legendFormat": "iEarn v2 AUM"
    }
   ]
  },
  {
   "title": "Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Earn's Share Price. If this goes up, that Earn product is compounding their yield gained from lending! This view helps normalize and show lending yield gained compared to other Earn products. The larger the spikes the more yield gain at that time from lending which was reinvested into the Earn product. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(iearn{param=\"price per share\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "graph",
   "description": "The current price of Earn's lp token should increase steadily as the lending yield is compounded in the Earn pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"price per share\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "y.curve.fi (v2) Earn - Share Price",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(iearn{param=\"price per share\", vault=~\".*v2\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "busd.curve.fi (v3) Earn - Share Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iearn{param=\"price per share\", vault=~\".*v3\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "graph",
   "description": "Amount in the Earn pool for each product. Amounts are shown in terms of the deposit token and not in the dollar amount. This shows lent-out and unlent-out coins for the pools.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"pooled balance\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Lent Out Supply",
   "type": "graph",
   "description": "Amount in the Earn pool for each product. Amounts are shown in terms of the deposit token and not in dollar amount. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"total supply\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Unlent Supply",
   "type": "graph",
   "description": "This shows the balance that has yet to be deposited into a lender protocol. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"available balance\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn - TVL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(iearn{param=\"tvl\"})",
     "legendFormat": "Earn v2 & v3 TVL"
    }
   ]
  }
 ]
}