{
 "title": "Ironbank Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Ironbank - Total Assets Under Management",
   "type": "stat",
   "description": "Ironbank AUM",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ironbank{param=\"tvl\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Supply APY",
   "type": "graph",
   "description": "The currently Supply APY for assets in Ironbank",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"supply apy\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Borrow APY",
   "type": "graph",
   "description": "The currently Borrow APY for assets in Ironbank",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"borrow apy\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Supply APY",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ironbank{param=\"supply apy\"} > 0)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Borrow APY",
   "type": "bargauge",
   "description": "Borrow APY > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ironbank{param=\"borrow apy\"} > 0)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Supplied",
   "type": "graph",
   "description": "Ironbank Total Supplied Assets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"total supplied\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Borrowed",
   "type": "graph",
   "description": "Ironbank Total Borrowed Assets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"total borrows\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank Utilization",
   "type": "bargauge",
   "description": "Utilization > 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ironbank{param=\"utilization\"} > 0)",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Ironbank - Utilization",
   "type": "graph",
   "description": "Ironbank Utilization\nPercent of funds available to be lent / funds being used. Utilization = totalBorrows / (getCash + totalBorrows - totalReserves)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Utilization (%)" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"utilization\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Cash",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"total cash\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Kept in Reserve from Lent Assets",
   "type": "graph",
   "description": "Total Kept in reserve from what is lent currently this is 5% of lent out assets. Assets with 0 value hidden.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Pool Shares kept in Reserve" }
   ],
   "targets": [
    {
     "expr": "ironbank{param=\"total reserves\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}