{
 "title": "Share Price",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "V1 - Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn{param=\"share price\", vault!=\"GUSD\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 - Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"share price\", vault!=\"GUSD\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V2 - Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V2 - Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "VE - Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_experimental{param=\"pricePerShare\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "VE - Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "yearn_experimental{param=\"pricePerShare\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn - Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(iearn{param=\"price per share\"}[1m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Earn - Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Share Price" }
   ],
   "targets": [
    {
     "expr": "iearn{param=\"price per share\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}