{
 "title": "V2 Vaults",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Value Locked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\"})",
     "legendFormat": "v2 AUM"
    }
   ]
  },
  {
   "title": "Price Per Share - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens! This helps normalize and show harvests compared to other vaults. The larger the spikes the more assets sold on that harvest call. The table shows the max value harvested for the timeframe selected. Note share price can dip when harvest is called as fees are collected and the harvest is paid out to vault holders over 6 hours to prevent sandwich attacks. This is a new feature of vault version 0.3.2",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(yearn_vault{param=\"pricePerShare\"}[2m])",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\"}",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Total Assets",
   "type": "graph",
   "description": "Amount of the deposit token in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"totalAssets\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Assets ($)",
   "type": "graph",
   "description": "Amount of the deposit asset in USD terms in the vault. This includes funds in all strategies + idle funds yet to be deployed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"} ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Value Locked",
   "type": "graph",
   "description": "This show Total Value Locked in v2 Vaults. If you see a quick sharp dip just ignore it, that isn't someone withdrawing and depositing quickly but a problem with the exporter at that time. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(yearn_vault{param=\"tvl\"})",
     "legendFormat": "v2 AUM"
    }
   ]
  },
  {
   "title": "Deposit Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"depositLimit\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Emergency Shutdown",
   "type": "stat",
   "description": "0 is no 1 is yes",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"emergencyShutdown\", job=\"yearn-v2\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Current Price of Token in USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"token price\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}