name: hadolint

on:
  push:

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hadolint
      uses: docker://hadolint/hadolint:latest
      with:
        args: 'hadolint --format tty Dockerfile'
